# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='travel_date_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='travel_date_to',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travelplanner_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='trips', to='login_app.User'),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
